import type { Metadata } from "next";
import "./globals.css";
import Footer from "./ui/footer";
import Head from "next/head";
import AutoThemeClass from "./components/AutoThemeClass";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-full bg-white dark:bg-darkBg">
        <AutoThemeClass />
        <div className="">
          <div className="min-h-screen">
            {children}
          </div>
          <div className="">
            <Footer></Footer>
          </div>
        </div>
      </body>
    </html>
  );
}
